version: "3.8"

services:
    postgres:
        build:
            context: ./
            dockerfile: Dockerfile
        container_name: my_app_postgres
        environment:
            POSTGRES_USER: ${POSTGRES_USER:-myuser}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-mypassword}
            POSTGRES_DB: ${POSTGRES_DB:-mydb}
        volumes:
            - postgres_data:/var/lib/postgresql/data
            - ./init:/docker-entrypoint-initdb.d
            - ./conf:/etc/postgresql
        ports:
            - "5432:5432"

volumes:
    postgres_data:
